name: Deploy billreader

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH connection
        shell: bash
        run: |
          echo "${{ secrets.SSH_KEY }}" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 -i /tmp/ssh_key ubuntu@161.118.167.226 "echo CONNECTED; hostname" 2>&1
